### ISSUE TITLE
I2P compatible services

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/appsI2P#17]
A category for apps, etc that are not written specifically for but work over I2P. Should these be in a sep category??

**Comment by eyedeekay** [comment]
Maybe, but it's potentially huge and also somewhat confusing. The two big divisions are "Apps that work over I2P and are known not to leak information about themselves" and "Apps that work over I2P and are not known to leak information about themselves. Almost everything falls into the latter category, and only a few things fall into the former.
