### ISSUE TITLE
Policies & Terms 

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/appsI2P#2]
Inclusion Policies for devs
Disclaimers
MIA ( Missing in action) policy
Terms and conditions

**Comment by Shoalsteed** [comment]
https://play.google.com/about/developer-content-policy/

https://extensionworkshop.com/documentation/publish/add-on-policies/

**Comment by eyedeekay** [comment]
Honestly, and I hate to say this, but on some levels it's probably better to be stricter. There are basically no circumstances where it would be acceptable to access location services, for instance. Logging unencrypted messages for any reason is probably also a big no-no, although maybe there's some situational reason that might make sense in context I can't think of right now. Maybe we need more opinions in the mix than mine on this one though, when it comes to apps I develop I can be pretty dogmatic.

**Comment by Shoalsteed** [comment]
How can any policy be reinforced?

**Comment by Shoalsteed** [comment]
https://f-droid.org/en/docs/Inclusion_How-To/

lots to consider

**Comment by Shoalsteed** [comment]
Regarding Disclaimers/ Use Policy: we will be mirroring, so maybe not necessary?

**Comment by Shoalsteed** [comment]
**Inclusion Policy**
