### ISSUE TITLE
Reasons For doing this

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/appsI2P#4]

**Comment by Shoalsteed** [comment]
All in one place for Apps and plugins and all things that add on to I2P.
Support devs to create things
Create community standards / new ways to be involved
Test and support each others code/ UX

**Comment by eyedeekay** [comment]
There are lots of existing I2P Applications which are catalogued only on a handful of sites, mostly sites that are run by either zzz or me, and neither of us calaog every single one, and neither of us use the same rules for cataloguing them except that we both catalog all plugins. zzz, for instance, catalogues every piece of software which bundles an I2P Router, and I only catalogue a handful of them. I catalog freestanding SAM applications, zzz doesn't catalogue all of them unless they bundle along a router. This is... horrible. It makes me like the plugin system by comparison. Which, to be fair, is a lot better once you get used to it. But it means the information about I2P applications is inconsistent even between people who mostly agree on things,

So there is value in a simple, I2P web service* which acts as a "Tracker/Proxy" for I2P applications and updates, on which arranges them by category, install type, intended functionality, conveniently displays descriptive information and which has the ability to allow users to issue comments on those apps, and which has the ability for administrators to moderate comments on those apps effectively. It should be able to either A) Know the difference between or B) Be configurably aware of  whether it's expected to work with an I2P router with plugin support.

**Comment by Shoalsteed** [comment]
Yes, this entirely.
I would like to add the idea of having an app specific dev hub. This can be my discord server, or it can be a new server since we can bridge w/irc.
